spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: byj.2410
    driver-class-name: com.mysql.jdbc.Driver

#mybatis showsql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
